ADMIN_SUBTYPES = (
    "country",
    "state-province",
    "district-county",
    "municipality",
    "locality",
    "neighbourhood",
)

SLUC_GADM_LEVELS = ["country", "state-province", "district-county"]

SLUC_CROPS = [
    "Banana",
    "Barley",
    "Bean",
    "Cassava",
    "Chickpea",
    "Coconut",
    "Cocoa",
    "Arabica Coffee",
    "Robusta Coffee",
    "Cotton",
    "Cowpea",
    "Groundnut",
    "Lentil",
    "Maize",
    "Pearl Millet",
    "Small Millet",
    "Oil Palm",
    "Pigeon Pea",
    "Plantain",
    "Potato",
    "Rapeseed",
    "Rice",
    "Sesame Seed",
    "Sorghum",
    "Soybean",
    "Sugarbeet",
    "Sugarcane",
    "Sunflower",
    "Sweet Potato",
    "Tea",
    "Tobacco",
    "Wheat",
    "Yams",
    "Other Cereals",
    "Other Fibre Crops",
    "Other Oil Crops",
    "Other Pulses",
    "Other Roots",
    "Rest of Crops",
    "Temperate Fruit",
    "Tropical Fruit",
    "Vegetables",
]

SLUC_GAS_TYPES = ["CO2e", "CO2", "CH4", "N20"]
